//
//  FrontPush-upExercise.swift
//  Generated by QuickPose Exercise Creator
//

import Foundation
import QuickPoseCore

// MARK: - Front Push-up Exercise Definition
class FrontPushupExercise {
    static func createExercise(hideFeedback: Bool = true) -> CustomExercise {
        let stages = [
        // Stage 1: Top Position (Arms Extended)
        ExerciseStage(
            id: "top_position",
            name: "Top Position",
            requirements: [
            .elbow(side: .right): AngleRange(min: 150, max: 210),
            .shoulder(side: .right): AngleRange(min: 10, max: 90),
            .elbow(side: .left): AngleRange(min: 150, max: 210),
            .shoulder(side: .left): AngleRange(min: 10, max: 90),
            ],
            description: "Arms extended at the top of the push-up"
        ),
        // Stage 2: Bottom Position (Arms Bent)
        ExerciseStage(
            id: "bottom_position",
            name: "Bottom Position",
            requirements: [
            .elbow(side: .right): AngleRange(min: 50, max: 110),
            .shoulder(side: .right): AngleRange(min: 50, max: 100),
            .elbow(side: .left): AngleRange(min: 50, max: 110),
            .shoulder(side: .left): AngleRange(min: 50, max: 100),
            ],
            description: "Arms bent at the bottom of the push-up"
        ),
        ExerciseStage(
            id: "Top Position",
            name: "Bottom Position",
            requirements: [
            .elbow(side: .right): AngleRange(min: 50, max: 110),
            .shoulder(side: .right): AngleRange(min: 50, max: 100),
            .elbow(side: .left): AngleRange(min: 50, max: 110),
            .shoulder(side: .left): AngleRange(min: 50, max: 100),
            ],
            description: "Arms bent at the bottom of the push-up"
        )
        ]
        
        // Define the required QuickPose features for range of motion tracking
        // Create custom styles for overlay
        let lightOverlayStyle = QuickPose.Style(relativeFontSize: 0.0, relativeArcSize: 0.3, relativeLineWidth: 1.0)
        let noOverlayStyle = QuickPose.Style(relativeFontSize: 0.0, relativeArcSize: 0.0, relativeLineWidth: 0.0)
        
        let requiredFeatures: [QuickPose.Feature] = [
        .rangeOfMotion(.elbow(side: .left, clockwiseDirection: true), style: lightOverlayStyle),
        .rangeOfMotion(.hip(side: .left, clockwiseDirection: true), style: noOverlayStyle),
        .rangeOfMotion(.knee(side: .left, clockwiseDirection: true), style: noOverlayStyle),
        .rangeOfMotion(.shoulder(side: .left, clockwiseDirection: false), style: lightOverlayStyle),
        .rangeOfMotion(.elbow(side: .right, clockwiseDirection: false), style: lightOverlayStyle),
        .rangeOfMotion(.hip(side: .right, clockwiseDirection: true), style: noOverlayStyle),
        .rangeOfMotion(.knee(side: .right, clockwiseDirection: true), style: noOverlayStyle),
        .rangeOfMotion(.shoulder(side: .right, clockwiseDirection: true), style: lightOverlayStyle),
        .overlay(.wholeBody, style: noOverlayStyle) // Light body outline
        ]
        
        return CustomExercise(
            id: "front_push-up",
            name: "Front Push-up",
            description: "Front Push-up",
            stages: stages,
            requiredFeatures: requiredFeatures,
            hideFeedback: hideFeedback
        )
    }
}
